site/api/urls.py
from wordapi.api.handlers import (
    UrlTokenHandler, RequestTokenHandler, 
    UrlFrequencyHandler, RequestFrequencyHandler,
    TagCloudBodyHandler, TagCloudUrlHandler,
    TagCloudFreqHandler,TagCloudFileHandler,
    CloudRetreiveHandler,
    )

from django.conf.urls.defaults import patterns, url
from piston.resource import Resource

urlpatterns = patterns('',
  # tokenize the contents of the url passed in the request                       
  url(r'^tokenize/url\.(?P<emitter_format>.+)$', Resource(UrlTokenHandler)),
  # tokenize the contents of the content passed in the request
  url(r'^tokenize/request\.(?P<emitter_format>.+)$', Resource(RequestTokenHandler)),
  # calculate the token frequency of the contents at the url passed in                       
  url(r'^frequency/url\.(?P<emitter_format>.+)$', Resource(UrlFrequencyHandler)),
  # calculate the token frequency of the contents passed in                       
  url(r'^frequency/request\.(?P<emitter_format>.+)$', Resource(RequestFrequencyHandler)),
  # build a tag cloud from the contents passed in 
  url(r'^tagcloud/body\.(?P<emitter_format>.+)$', Resource(TagCloudBodyHandler)),
  # build a tag cloud from the url passed in 
  url(r'^tagcloud/url\.(?P<emitter_format>.+)$', Resource(TagCloudUrlHandler)),
  # build a tag cloud from the json-encoded dictionary of frequencies passed in 
  url(r'^tagcloud/freq\.(?P<emitter_format>.+)$', Resource(TagCloudFreqHandler)),
  # retreive a tag cloud
  url(r'^cloud/(?P<cloud_id>[0-9A-Za-z]+)\.(?P<emitter_format>.+)$', Resource(CloudRetreiveHandler)),
  # build a tag cloud from the file uploaded
  url(r'^tagcloud/file\.(?P<emitter_format>.+)$', Resource(TagCloudFileHandler)),

)

site/frontend/urls.py
from django.conf.urls.defaults import patterns, url
from django.views.generic.simple import direct_to_template
from frontend.views import *

urlpatterns = patterns('',
    url(r'^learn', direct_to_template, {'template': 'frontend/learn.html'}),
    url(r'^create', direct_to_template, {'template': 'frontend/create.html'}),
    url(r'^examples', direct_to_template, {'template': 'frontend/examples.html'}),
    url(r'^browse', direct_to_template, {'template': 'frontend/browse.html'}),
    # need the trailing $ after api since the api calls start with /api too
    url(r'^api$', direct_to_template, {'template': 'frontend/api.html'}),

    url(r'^cloud/(?P<cloud_id>\w+)', cloud),
    url(r'^topic/new$', new_topic),
    url(r'^document/new$', new_document),
    url(r'^collecion/new$', new_collection),
#  url(r'^login'),
    url(r'^$',  direct_to_template, {'template': 'frontend/index.html'}),

)

site/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^wordfrontend/', include('wordfrontend.foo.urls')),
    url(r'^%s/(?P<path>.*)$' % settings.MEDIA_URL.strip('/'), 
        'django.views.static.serve', {'document_root': settings.MEDIA_ROOT }),
    (r'^api/1.0/', include('api.urls')),
    (r'^', include('frontend.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),
)

site/api/models.py
from django.db import models

# Create your models here.

''' 
Some algorithms build a statistical model of a single topic. What are the most
frequent/high entropy words in this set of documents? A single topic model can
be used to form a classifier 

supervised/unsupervised --> topic models --> classifiers / results
'''

# classifier methods take a document and return the most similar topic, by the
# method specified.
    
def kmeans():
    pass

def lda():
    pass

def cosine_similarity():
    pass

def tfidf_similarity():
    pass

def difference():
    pass

def entropy():
    pass


class Scheduler(object):
    '''Scheduler lets you manage when and how source documents are retrieved
    to update a model or classifier. You might want to gather docs once an hour
    for 3 days, or every Monday indefinitely, or every night at midnight.
    Schedules can be registered with any model, topic or classifier type. '''
    pass

class DocumentSet(object):
    ''' A document set is used to build a set of topic models from one or more
    source documents.'''
    pass 

class Topic(object):
    sources = []
    created = None
    last_updated = None
    update = None #static, manual, auto
    model = None # tfidf, regular freq, k-means...
    public = False

class Source(object):
    uri = None
    created = None
    updated = None

site/frontend/models.py
from django.db import models

# Create your models here.

site/frontend/forms.py
from django import forms

# default is required = True
class TagCloudForm(forms.Form):
	help_text = {
			# input type
			'body' : 'Paste your text inline (eg. into this box)',
			'url' : 'Retrieve text from the specified url.',
			'file' : 'Upload a file',
			'freqs' : "Enter in a dictionary of word:frequency counts",

			# required info
			'width' : 'Width of the div containing the tag cloud (px). Default none.',
			'height' : 'Height of the div containing the tag cloud (px). Default None.',
			'max_words' : 'Maximum number of words to be included in the tag cloud (will always truncate least frequent words)',

			# advanced options
			'strip' : 'Strip any html markup. Default is True.',
			'normalize' : "Normalize the case of all words, making 'Hello' and 'hello' equivalent",
			'stopwords' : "Remove (exclude) common english words (so-called 'stop words'), such as 'the' and 'it'. Default True.",
			'custom_stopwords': 'a comma separated list of custom stop words. can be used in addition to, or instead of, standard english stopwords.',
			'tokenizer' : 'Specify a custom tokenizer, by passing in a <a href="http://docs.python.org/library/re.html">python regular expression</a>',
			'sort_order' : 'What order should the words be sorted in?',
			'equation': 'Equation family to use for extrapolation of word sizes. options are "linear," "log," and "exp."',
			'slope': 'If a linear equation style is chosen, the slope can be customized (default 0.15).',
			'css_id': 'a custom css id to include in the div for the word cloud',
			'css_class': 'a custom css class to include for each word in the word cloud.',
			'link_to': 'each word in the word cloud can be a link. if so, specify the link prefix here. (eg. if each word is a category, the tag cloud can link to that category page by inserting the url prefix here). specify "wordnik" to link to fun wordnik definitions.',
			'layout': 'layout algorithm: either svg (recommended) or text',
			}

	allowed_sort_orders = [('random', 'random'), ('frequency', 'frequency'),
			('alphabetical', 'alphabetical')]

	allowed_layouts = [('svg', 'svg'), ('text', 'text')]

	body = forms.CharField(widget=forms.Textarea(attrs={'rows':'20', 'cols':60 }), help_text = help_text['body'], required=False, label="Text")
	url =           forms.CharField(help_text = help_text['url'], required=False)
	file =          forms.FileField(help_text = help_text['file'], required=False)
	# this is an option in the API but not likely to be useful in the frontend
	#freqs =         forms.CharField(help_text = help_text['freqs'], required=False)

	# required
	width =         forms.IntegerField(help_text = help_text['width'], required=False)
	height =        forms.IntegerField(help_text = help_text['height'], required=False)
	max_words =     forms.IntegerField(help_text = help_text['max_words'], required=False)

	# aesthetics
	start_color =   forms.CharField(required=False)
	end_color =     forms.CharField(required=False)
	color_steps =   forms.IntegerField(required=False)

	# word handling
	strip =         forms.BooleanField(initial=True, help_text = help_text['strip'], required=False)
	normalize =     forms.BooleanField(initial=True, help_text = help_text['normalize'], required=False)
	remove_stopwords = forms.BooleanField(initial=True, help_text = help_text['stopwords'], 
			required=False)
	custom_stopwords = forms.CharField(help_text = help_text['custom_stopwords'], 
			required=False)
	tokenizer =     forms.CharField(help_text = help_text['tokenizer'], required=False)
	sort_order =    forms.ChoiceField(help_text= help_text['sort_order'], required=False, 
			choices = allowed_sort_orders)
	equn =			forms.CharField(help_text=help_text['equation'], required=False)
	slope =			forms.FloatField(help_text=help_text['slope'], required=False)
	css_id =		forms.CharField(help_text=help_text['css_id'], required=False)
	css_class =		forms.CharField(help_text=help_text['css_class'], required=False)
	link_prefix	=	forms.CharField(help_text=help_text['link_to'], required=False)
	layout =		forms.ChoiceField(help_text= help_text['layout'], required=False, 
			choices = allowed_layouts)


	def clean(self):
		cleaned_data = self.cleaned_data
		url = cleaned_data.get('url')
		body = cleaned_data.get('body')
		file = cleaned_data.get('file')
		if not url and not body and not file:
			raise forms.ValidationError('You must specify one of "url", "body" or "file" fields')
		if (url and body) or (url and file) or (body and file):
			raise forms.ValidationError('Specify only one of "url" or "body" or "file" fields')

		# if specifying color, need all three of start_color, end_color and
		# color_steps.
		start_color = cleaned_data.get('start_color')
		end_color = cleaned_data.get('end_color')
		color_steps = cleaned_data.get('color_steps')
		if start_color or end_color or color_steps:
			if not (start_color and end_color and color_steps):
				raise forms.ValidationError('To customize the color scheme, please enter all color scheme information: start color, end color, and number of steps to extrapolate in between.')
		
		return cleaned_data

class NewTopicForm(forms.Form):
	name = forms.CharField()

	def __init__(self, *args, **kwargs):
		num_file_sources = kwargs.pop('file_sources', None)
		num_web_sources = kwargs.pop('web_sources', None)
		print num_file_sources
		print num_web_sources
		super(NewTopicForm, self).__init__(*args, **kwargs)
		while num_file_sources:
			self.fields['file_%d' % num_file_sources] = forms.FileField()
			num_file_sources -= 1
		while num_web_sources:
			self.fields['web_%d' % num_web_sources] = forms.CharField()
			num_web_sources -= 1

site/api/views.py
# Create your views here.

site/frontend/views.py
# Create your views here.
from django.conf import settings
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse
from django.core.context_processors import csrf
from frontend.forms import TagCloudForm, NewTopicForm
import urllib, httplib2, datetime, re
import pymongo
import pymongo
from pymongo.objectid import ObjectId
try:
    import json
except:
    import simplejson as json

def render_to_formtemplate(request, template, kwargs={}):
    ''' Add csrf token, then call the regular render_to_template'''
    kwargs.update(csrf(request))
    return render_to_template(request, template, kwargs)

def render_to_template(request, template, kwargs={}):
    # calls the RequestContext which populates with default template variables
    return render_to_response(template, kwargs, 
                context_instance=RequestContext(request))



def new_document(request):
    if request.method == 'GET':
        form = TagCloudForm()
        return render_to_formtemplate(request, 'frontend/newdoc.html', 
                {'domain': settings.API_URL,'tagcloud_form' : form })

    else:
        form = TagCloudForm(request.POST, request.FILES)
        print request.FILES
        # validation function just checks required fields for now, but later should
        # probably validate tokenizer regular expressions etc. 
        if form.is_valid(): 
            data = form.cleaned_data
            args = {}
            for field, value in data.iteritems():
                if value:
                    args[field] = value
            
            if 'file' in args:
                url = settings.API_URL + "/api/1.0/tagcloud/file.json"
                fp = request.FILES['file']
                tmp_file = ''
                for chunk in fp.chunks():
                    tmp_file += chunk 
                args['file'] = tmp_file

            elif 'body' in args:
                url = settings.API_URL + "/api/1.0/tagcloud/body.json"
                #  normalize the character encoding on any input text
                args['body'] = args['body'].encode('ascii', 'replace')

            elif 'freqs' in args:
                url = settings.API_URL + "/api/1.0/tagcloud/freq.json"

            else: # this is a 'url' call
                url = settings.API_URL + "/api/1.0/tagcloud/url.json"

            # XXX this is a temporary hack until we get the ajax-y resize
            # working. set the max_words and div size to something reasonable. 
            args['max_words'] = 100
            
            print 'data arguments'
            headers = {'Content-type': 'application/x-www-form-urlencoded',
                        'enctype': 'enctype="multipart/form-data"'}
            args = urllib.urlencode(args)
            print args
            http = httplib2.Http()
            print 'about to make api call to %s' % url
            response, content = http.request(url, 'POST', headers=headers, body=args)
            try:
                js = json.loads(content)
                body = js['body']
                style = js['style']
                metadata = js['metadata']
                cloud_id = js['_id']
            except:
                return HttpResponse('<b>API Error</b><br><br>'+content)
                return

            return HttpResponseRedirect("/cloud/%s" % cloud_id)
        else:
            print request.POST
            print 'Form did not validate'
            form = TagCloudForm(request.POST)
            return render_to_formtemplate(request, 'frontend/newdoc.html', 
                                        {'domain': settings.API_URL,
                                        'tagcloud_form' : form
                                        })

def cloud(request, cloud_id):

    print cloud_id
    if re.search('[^0-9a-zA-Z]', cloud_id):
        return HttpResponse('Invalid Cloud ID')

    url = settings.API_URL + '/api/1.0/cloud/' + cloud_id + '.json'
    print 'retrieving cloud...'
    print url
    http = httplib2.Http()
    response, content = http.request(url, 'GET')
    try:
        record = json.loads(content)
    except:
        return HttpResponse('<b>API Error</b><br><br>'+content)

    # XXX TODO this needs to be its own form, not the tag cloud form. 
    form = TagCloudForm()

    #generator_url = url + '?' + urllib.urlencode(control_params)
    # tell the browser where it can insert a line break
    #generator_url_display = generator_url.replace('&', '<wbr>&')

     # note that in the template, body and style need to be given the 'safe'
    # filter so that the markup will be interpreted. otherwise it will be
    # escaped and displayed as strings.
    return render_to_template(request, 'frontend/cloud.html', {'cloud':record, 'update_form':form})

def new_topic(request):
    #topic_form = NewTopicForm(request.POST)
    if request.method == 'POST':
        # get the fields and construct a form to match
        form_data = request.POST
        print form_data
        topic_form = topic_form_generator(form_data)
        return render_to_formtemplate(request, 'frontend/newtopic.html', {'topic_form': topic_form})
        # ---> compute stats --> redirect to topic homepage<br>
    else:
        return render_to_formtemplate(request, 'frontend/newtopic.html')

def topic_form_generator(form_data):
    file_sources = 0
    web_sources = 0
    for k,v in form_data.iteritems():
        if 'web_source' in k:
            web_sources += 1
        elif 'file_source' in k:
            file_sources += 1
    return NewTopicForm(form_data, file_sources=file_sources, 
            web_sources=web_sources)


def topic(request, topic_id):
    # if !saved:
    #   message: this topic has not yet been saved! click here to save
    #vocab, wordcloud, graph of frequency<br>
    #add a classifier<br>
    pass

#def new_document(request):
#    pass

def new_collection(request):
    pass


#def save(request):
#    if request.method == 'GET':
#        return HttpResponseRedirect("/")
#
#    # save data and url to db
#    data = request.POST.get('data')
#    record = json.loads(data)
#    record['created'] = datetime.datetime.now()
#    record['update_type'] = request.POST.get('update')
#    if request.POST.get('name', None):
#        record['cloud_name'] = request.POST.get('name')
#    # record['owner'] = username
#    # record['permissions'] = public
#    
#    # create the unique id for this record
#    oid = ObjectId()
#    uid = str(oid)
#    record['_id'] = oid
#    # create short link
#    long_url = settings.HOME_PAGE + '/cloud/' + uid
#    short_url = bitly_shorten(long_url)
#    print short_url
#    record['short_url'] = short_url
#    con = pymongo.Connection()
#    collection = con.wordapi.tagclouds
#    collection.insert(record)
#
#    # redirect to the cloud's page
#    return HttpResponseRedirect("/cloud/%s" % uid)
#
#    # a dynamic tagcloud saves the source information and rendering preferences

site/templates/frontend/api.html
{% extends "frontend/base.html" %}


{% block content %}

WordAPI is a standalone, restful API offering document and topic analysis for the web.

<h2>Available Methods</h2>

<h3>Frequency - URL</h3>

Supported Requests: GET

<h3>Frequency - Request</h3>

Supported Requests: GET, POST

<h3>Tokenize - URL </h3>

Supported Requests: GET

<h3>Tokenize - Request </h3>

Supported Requests: GET, POST

<h3>TagCloud - Request </h3>

<p>Supported Requests: GET, POST</p>

<h4>Parameters</h4>
<ul>
	<li> width and height
	<li> color 
	<li>
	<li>
	<li>
	<li>
	<li>
	<li>
	<li>
	<li>
	<li>
</ul>

<a href="/tagcloud">Details and try it!</a>

{% endblock %}

site/templates/frontend/cloud.html
{% extends "frontend/base.html" %}

{% block custom_include %}
<link rel="stylesheet" media="screen" type="text/css" href="/media/colorpicker.css" />
<script type="text/javascript" src="/media/js/colorpicker.js"></script>
{% endblock %}
{% block page_title %} - TagCloud{% endblock %}

{% block content %}
<div id="save-box">
<form id="save-form" action="save" method="POST">
{% csrf_token %}
<label for="name">Name your cloud (optional)</label>
<input type="text" name="name"><br>
<fieldset id="update-type">
<input type="radio" name="update" value="static" checked="yes">Static
<input type="radio" name="update" value="dynamic">Dynamic<br>
<p>A static cloud stays the same as you see it right now. A dynamic cloud will
update every time you visit it.</p> 
</fieldset>
<input type="hidden" name="cloud_id" value="{{ cloud_id }}">
</form>
</div>

<div id="tagcloud_controls">
  <h4>Themes</h4>
  <h4>Color</h4>
  {{ update_form.start_color.label }}: <input type="text" maxlength="6" size="6" id="id_start_color" value="00ff00" />
  {{ update_form.end_color.label }}: <input type="text" maxlength="6" size="6" id="id_end_color" value="0000ff" />
  {{ update_form.color_steps.label }}: {{ update_form.color_steps }}
      
  <h4>{{ update_form.max_words.label }}: <input type="range"  min="0" max="{{ cloud.metadata.total_tags }}" /></h3>
  <h4 class="size-selector">Size:</h4>
    <label><input class="radio" type="radio" name="size" value="240x180"> Small</label>
    <label><input class="radio" type="radio" name="size" value="500x375"> Medium</label>
    <label><input class="radio" type="radio" name="size" value="1024x768"> Large</label>
  
  <h4>Custom Stop Words</h4>
</div>

<div id="tagcloud_wrapper">
	{{ cloud.style|safe }}
	{{ cloud.body|safe}}
	{{ cloud.wordcloud_size|safe}}
	<!-- {{ cloud.script|safe}} -->
</div>

<div class="clear">
</div>

<div id="infobox">
Generated by <a href="{{home_page}}">WordAPI</a>
Created {{ cloud.utc_created|date:"D M d, Y" }}. 
<a href="{{ cloud.metadata.short_url }}">Short Url</a>
<a href="">Embed</a>
<a href="{{home_page}}/document/new">Create your own</a>

</div>

{% endblock %}

site/templates/frontend/examples.html
{% extends "frontend/base.html" %}


{% block content %}
<div id="usecases">
<ul>
<li>How many distinct words are on this page?</li>
<li>What are the most frequent words in the NYT Business section?</li>
<li>I want to make a dynamically updating tag cloud of my employees' status
reports</li> 
<li>Tag cloud of all my RSS feeds over time, updated with each new article</li>
<li>What topic is this tweet most similar to?</li>
<li>How are the most frequent words on twitter changing over time?</li>
<li>Was this speech given by Obama or Bush?</li>
<li>What words appear most frequently in the edits to a given Wikipedia page?</li>
<li>WHat are the most frequent terms in all courses on p2pu.org</li>
</ul>
</div>

{% endblock %}

site/templates/frontend/newdoc.html
{% extends "frontend/base.html" %}

{% block custom_include %}
<link rel="stylesheet" media="screen" type="text/css" href="/media/colorpicker.css" />
<script type="text/javascript" src="/media/js/colorpicker.js"></script>
{% endblock %}

{% block custom_js %}
<script type="text/javascript">
window.selectIngest = function(clickedSelector, ingestInputToShow){
  // select the correct ingest-selector
  var ingestSelectors = jQuery('#ingest-selector-container').children('a.ingest-selector');
  jQuery.each(ingestSelectors, function(i, currSelector){
    if (currSelector == clickedSelector) {
      jQuery(currSelector).addClass("selected");
    } else {
      jQuery(currSelector).removeClass("selected");
    }
  });
  // Show the correct input
  var ingestInputs = ['#url-ingest', '#file-ingest', '#text-ingest'];
  jQuery.each(ingestInputs, function(i, currIngestInput){
    var shouldShow = ingestInputToShow == currIngestInput;
    jQuery(currIngestInput).toggle(shouldShow);
  });
};

$('#id_start_color, #id_end_color').ColorPicker({
	onSubmit: function(hsb, hex, rgb, el) {
		$(el).val(hex);
		$(el).ColorPickerHide();
	},
	onBeforeShow: function () {
		$(this).ColorPickerSetColor(this.value);
	}
})
.bind('keyup', function(){
	$(this).ColorPickerSetColor(this.value);
});

</script>
{% endblock %}

{% block content %}

  <form class="ingest" action="" method="post" enctype="multipart/form-data"> {% csrf_token %}

	  <fieldset>
		  <legend>Input Type</legend>
		  <div id="ingest-selector-container">
			  <a href="#" class="ingest-selector selected" onclick="selectIngest(this, '#url-ingest'); return false;">
				  <img src="/media/images/process.png">
				  <h3>
					  {{ tagcloud_form.url.label }}
				  </h3>
				  <div class="detail-text">
					  {{ tagcloud_form.url.help_text }}
				  </div>    
			  </a>
			  <a href="#" class="ingest-selector" onclick="selectIngest(this, '#file-ingest'); return false;">
				  <img src="/media/images/process.png">
				  <h3>
					  {{ tagcloud_form.file.label }}
				  </h3>
				  <div class="detail-text">
					  {{ tagcloud_form.file.help_text }}
				  </div>
			  </a>
			  <a href="#" class="ingest-selector" onclick="selectIngest(this, '#text-ingest'); return false;">
				  <img src="/media/images/process.png">
				  <h3>
					  {{ tagcloud_form.body.label }}
				  </h3>
				  <div class="detail-text">
					  {{ tagcloud_form.body.help_text }}
				  </div>
			  </a>
		  </div>
		  <div id="url-ingest" class="ingest-input-container">
			  {{ tagcloud_form.url }}
		  </div>
		  <div id="file-ingest" class="ingest-input-container" style="display:none;">
			  {{ tagcloud_form.file }}
		  </div>
		  <div id="text-ingest" class="ingest-input-container" style="display:none;">
			  {{ tagcloud_form.body }} 
		  </div>
	  </fieldset>
    

  <div class="clear"></div>
  <fieldset><legend>Word Cloud Size</legend>
	 <div class="step_option_input">
        {{ tagcloud_form.width.label }}: {{ tagcloud_form.width }}
     </div>
	 <div class="step_option_help">
       {{ tagcloud_form.width.help_text }}
     </div>
	 <br>
	 <div class="step_option_input">
       {{ tagcloud_form.height.label }}: {{ tagcloud_form.height }}
     </div>
	 
	 <div class="step_option_help">
       {{ tagcloud_form.height.help_text }}
     </div>
 </fieldset>

 <fieldset><legend>Number of Words</legend>
      <div class="step_option_input">
        {{ tagcloud_form.max_words.label }}: {{ tagcloud_form.max_words }}
      </div>
      <div class="step_option_help">
        {{ tagcloud_form.max_words.help_text }}
      </div>
  </fieldset>

  <fieldset><legend>Colors</legend>
       <div class="step_option_input">
          {{ tagcloud_form.start_color.label }}: {{ tagcloud_form.start_color }}
       </div>
       <div class="step_option_help">
         {{ tagcloud_form.start_color.help_text }}
       </div>
       <br>
       <div class="step_option_input">
         {{ tagcloud_form.end_color.label }}: {{ tagcloud_form.end_color }}
       </div>
       <div class="step_option_help">
         {{ tagcloud_form.end_color.help_text }}
       </div>
       <br>
       <div class="step_option_input">
         {{ tagcloud_form.color_steps.label }}: {{ tagcloud_form.color_steps }}
       </div>
       <div class="step_option_help">
         {{ tagcloud_form.color_steps.help_text }}
       </div>
   </fieldset>

   <fieldset><legend>Advanced formatting and word handling options</legend>
       <div class="step_option_input">
         {{ tagcloud_form.strip.label }}: {{ tagcloud_form.strip }}
       </div>
       <div class="step_option_help">
         {{ tagcloud_form.strip.help_text }}
	 </div>
	 <br>
       <div class="step_option_input">
         {{ tagcloud_form.normalize.label }}: {{ tagcloud_form.normalize }}
       </div>
       <div class="step_option_help">
         {{ tagcloud_form.normalize.help_text }}
       </div>

	 <br>
       <div class="step_option_input">
         {{ tagcloud_form.remove_stopwords.label }}: {{ tagcloud_form.remove_stopwords }}
       </div>
       <div class="step_option_help">
         {{ tagcloud_form.remove_stopwords.help_text }}
       </div>

	 <br>
       <div class="step_option_input">
         {{ tagcloud_form.custom_stopwords.label }}: {{ tagcloud_form.custom_stopwords }}
       </div>
       <div class="step_option_help">
         {{ tagcloud_form.custom_stopwords.help_text }}
       </div>

	 <br>
       <div class="step_option_input">
         {{ tagcloud_form.tokenizer.label }}: {{ tagcloud_form.tokenizer }}
       </div>
       <div class="step_option_help">
         {{ tagcloud_form.tokenizer.help_text }}
       </div>

	 <br>
       <div class="step_option_input">
         {{ tagcloud_form.sort_order.label }}: {{ tagcloud_form.sort_order }}
       </div>
       <div class="step_option_help">
         {{ tagcloud_form.sort_order.help_text }}
       </div>

	 <br>
       <div class="step_option_input">
         {{ tagcloud_form.equn.label }}: {{ tagcloud_form.equn }}
       </div>
       <div class="step_option_help">
         {{ tagcloud_form.equn.help_text }}
       </div>

	 <br>
       <div class="step_option_input">
         {{ tagcloud_form.slope.label }}: {{ tagcloud_form.slope }}
       </div>
       <div class="step_option_help">
         {{ tagcloud_form.slope.help_text }}
       </div>

	 <br>
       <div class="step_option_input">
         {{ tagcloud_form.css_id.label }}: {{ tagcloud_form.css_id }}
       </div>
       <div class="step_option_help">
         {{ tagcloud_form.css_id.help_text }}
       </div>

	 <br>
       <div class="step_option_input">
         {{ tagcloud_form.css_class.label }}: {{ tagcloud_form.css_class }}
       </div>
       <div class="step_option_help">
         {{ tagcloud_form.css_class.help_text }}
       </div>

	 <br>
       <div class="step_option_input">
         {{ tagcloud_form.link_prefix.label }}: {{ tagcloud_form.link_prefix }}
       </div>
       <div class="step_option_help">
         {{ tagcloud_form.link_prefix.help_text }}
       </div>

	 <br>
       <div class="step_option_input">
         {{ tagcloud_form.layout.label }}: {{ tagcloud_form.layout }}
       </div>
       <div class="step_option_help">
         {{ tagcloud_form.layout.help_text }}
       </div>

   </fieldset>

	 <br>
	 <br>

    <button type="submit" class="ingest-submit"><h3>Create Word cloud!</h3></button>

</form>

{% endblock %}